# Generated by Django 3.2.25 on 2024-08-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(max_length=120),
        ),
    ]
